"""add summary column

Revision ID: 72675d407b0c
Revises: add_doctype_models
Create Date: 2026-03-14 07:15:08.748031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72675d407b0c'
down_revision: Union[str, None] = 'add_doctype_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doctypes_name_key', 'doctypes', type_='unique')
    op.add_column('tool_jobs', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('tool_jobs', sa.Column('execution_time', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_jobs', 'execution_time')
    op.drop_column('tool_jobs', 'summary')
    op.create_unique_constraint('doctypes_name_key', 'doctypes', ['name'])
    # ### end Alembic commands ###
